using System;
using TransportManager.Enums;

namespace TransportManager.Entities.Contracts
{
    // Definition of a contract. Dynamically generated by ContractGenerator.
    // Plain Serializable class (no longer a ScriptableObject) so it can be
    // embedded inside ContractInstance and persisted in the save file.
    [Serializable]
    public class ContractData
    {
        public string id;
        public string displayName;
        public ContractDifficulty difficulty;

        public string originCityId;
        public string destinationCityId;
        public string originAddressLabel;
        public string destinationAddressLabel;

        public float distanceKm;
        public float baseDurationSeconds;   // ORS-reported duration for reference

        public int requiredCapacity;        // min vehicle capacity (= cargoTons)
        public int baseReward;

        public int cargoTons;               // quantity of goods to haul
        public string cargoLabel;           // short description of the goods
    }
}
